LORENZ_DATA:
  DELTA T: 0.1
  NORMALISED: false
  SIGNAL TO NOISE RATIO: 0
  TOTAL_N: 17500
  T_0: 0
  T_END: 1750
  T_TRANS: 750
  WINDOW_SIZE: 100
ML_CONSTRAINTS:
  ACTIVATION: Tanh
  BATCH_SIZE: 256
  CLOOP-TRAINED: false
  DROPOUT: 0.0
  EPOCH_ITER: 10
  EPOCH_STEPS: 1000
  L2: 0
  LR: 0.001
  N_CELLS: 10
  N_EPOCHS: 10000
  OLOOP-TRAINED: true
  OPTIMIZER: Adam
  PHYSICS INFORMED: true
  PHYSICS WEIGHT: 0.0
