import os
import tensorflow as tf


def tensorflow_shutup() -> None:
    """ Makes Tensorflow less verbose by setting the logging level to 'ERROR' and monkey-patching
        the deprecation utility to silence deprecation warnings.
        This function is intended to be used in development environments where you want to reduce the 
        amount of output generated by Tensorflow, without having to change the logging settings manually.
        It simply sets some environment variables and imports some Tensorflow modules, and then performs
        some operations to silence Tensorflow's output.
    """
    try:
        os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

        # noinspection PyPackageRequirements
        import tensorflow as tf
        from tensorflow.python.util import deprecation

        tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

        # Monkey patching deprecation utils to shut it up! Maybe good idea to disable this once after upgrade
        # noinspection PyUnusedLocal
        def deprecated(date, instructions, warn_once=True):  # pylint: disable=unused-argument
            def deprecated_wrapper(func):
                return func
            return deprecated_wrapper

        deprecation.deprecated = deprecated

    except ImportError:
        pass
