DATA:
  DELTA T: 0.25
  NORMALISED: false
  SIGNAL TO NOISE RATIO: 0
  TOTAL_N: 99000
  TRAINING RATIO: 0.67
  T_0: 0
  T_END: 25000
  T_TRANS: 250
  UPSAMPLING: 1
  VALID RATIO: 0.17
  WINDOW_SIZE: 20
ML_CONSTRAINTS:
  ACTIVATION: Tanh
  BATCH_SIZE: 64
  DROPOUT: 0.0
  EPOCH_STEPS: 100
  LR: 0.001
  N_CELLS: 200
  N_EPOCHS: 1000
  OLOOP-TRAINED: true
  OPTIMIZER: Adam
  PI WEIGHT: 100
  REG WEIGHT: 1.0e-09
