LORENZ_DATA:
  DELTA T: 0.01
  NORMALISED: false
  SIGNAL TO NOISE RATIO: 0
  TOTAL_N: 17600
  T_0: 0
  T_END: 1760
  T_TRANS: 10
  WINDOW_SIZE: 50
ML_CONSTRAINTS:
  ACTIVATION: Tanh
  BATCH_SIZE: 256
  CLOOP-TRAINED: false
  DROPOUT: 0.0
  EPOCH_ITER: 10
  EPOCH_STEPS: 500
  L2: 0
  LR: 0.001
  N_CELLS: 100
  N_EPOCHS: 10000
  OLOOP-TRAINED: true
  OPTIMIZER: Adam
  PHYSICS INFORMED: true
  PHYSICS WEIGHT: 0.0
