DATA:
  DELTA T: 0.01
  NORMALISED: false
  SIGNAL TO NOISE RATIO: 0
  TOTAL_N: 8000
  TRAINING RATIO: 0.25
  T_0: 0
  T_END: 100
  T_TRANS: 20
  VALID RATIO: 0.1
  WINDOW_SIZE: 20
ML_CONSTRAINTS:
  ACTIVATION: Tanh
  BATCH_SIZE: 256
  DROPOUT: 0.0
  EPOCH_STEPS: 500
  L2: 0
  LR: 0.001
  N_CELLS: 50
  N_EPOCHS: 5000
  OLOOP-TRAINED: true
  OPTIMIZER: Adam
  PHYSICS WEIGHT: 0.0
