DATA:
  DELTA T: 0.01
  NORMALISED: false
  SIGNAL TO NOISE RATIO: 0
  TOTAL_N: 42500
  TRAINING RATIO: 0.4
  T_0: 0
  T_END: 425
  T_TRANS: 100
  UPSAMPLING: 1
  VALID RATIO: 0.1
  WINDOW_SIZE: 20
ML_CONSTRAINTS:
  ACTIVATION: Tanh
  BATCH_SIZE: 128
  DROPOUT: 0.0
  EPOCH_STEPS: 200
  LR: 0.001
  N_CELLS: 100
  N_EPOCHS: 5000
  OLOOP-TRAINED: true
  OPTIMIZER: Adam
  PI WEIGHT: 0.0001
  REG WEIGHT: 1.0e-09
